const string TRANSMISSION_RADIO_CONFIG_ROOT_SERVER = "$profile:EA_TransmissionRadio\\";
const string TRANSMISSION_RADIO_CONFIG_DIR_SERVER = TRANSMISSION_RADIO_CONFIG_ROOT_SERVER + "Config\\";
const string TRANSMISSION_RADIO_CONFIG = TRANSMISSION_RADIO_CONFIG_DIR_SERVER + "EA_TransmissionRadioConfig.json";
